<?php

namespace Blogger\BlogBundle\Repository;

/**
 * EnquiryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnquiryRepository extends \Doctrine\ORM\EntityRepository
{
}
