blogger_blog_homepage:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }

blogger_blog_about:
    path:     /about
    defaults: { _controller: BloggerBlogBundle:Page:about }

blogger_blog_contact:
    path:     /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }

blogger_blog_show:
    path:  /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
          id: \d+
blogger_blog_comment_create:
    path: /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
          blog_id: \d+
blogger_blog_sidebar:
     path:  /sidebar
     defaults: { _controller: BloggerBlogBundle:Page:sidebar }